# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ee8e8b09bf73d58234c6878ddb8bddaada889f9a93d15ac35d0fdb3bceb2194f861bf7871adcc3d7515e6c509b629702a71076e4366689c634560584e78531c
  facebook_api_id: 1498086897073314
  facebook_api_secret: c474ab9a4c98f37e6e1ad9ce3136104d

test:
  secret_key_base: 01030b8449a9f0e57ed036b085fac3ebde0c28cb5a5a6dbed7e8a9eb5adb3de70204544f4ba403c760785c6d2a43b5260dae3d9b763b25e5f3a481a646cc4afd
  facebook_api_id: 1498086897073314
  facebook_api_secret: c474ab9a4c98f37e6e1ad9ce3136104d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

